<?php

include '../assets/conn.php';

$url = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
$parts = parse_url($url);
$output = [];
parse_str($parts['query'], $output);

$paadhar = $output['aadhar'];
$sql = "SELECT * FROM patient where aadhar='$paadhar';";
$result = mysqli_query($conn, $sql);
$errorr = mysqli_error($conn);

if ($errorr) {
    echo "User doesn't Exists ";
} else {
    if (mysqli_num_rows($result)) {
        $rows = mysqli_fetch_assoc($result);

        echo '
        <center>
        <h1>Siddaganga Instute of Technology</h1>
        <h2>Online E-Health records</h2>
        <h2>Report generated by the computer using Machine Learing Techniques</h2>
        <br>
        <hr>
        <table style="width:40%;text-align:center;">
        <tr>
        <td>Name</td>
        <td>' . $rows["name"] . '</td>
        </tr>
        <tr>
        <td>Patient ID</td>
        <td>' . $rows["id"] . '</td>
        </tr>
        <tr>
        <td>Father Name</td><td>' . $rows["father"] . '</td>
        </tr>
        <tr> 
        <td>Mother Name</td><td>' . $rows["mother"] . '</td>
        </tr>
        <tr> 
        <td>Gender</td><td>' . $rows["gender"] . '</td>
        </tr>
        <tr><td>blood group</td><td>' . $rows["blood"] . '</td></tr>
        <tr>
        <td>
        DOB</td> <td>' . $rows["dob"] . '</td></tr>
        <tr><td>Mobile</td> <td>' . $rows["mobile"] . '</td></tr>
        </table>
        </center>
        ';

        $sql = "SELECT * FROM diabetes_sym where aadhar='$paadhar' order by dateTime desc;";
        $result = mysqli_query($conn, $sql);

        $errorr = mysqli_error($conn);
        if ($errorr) {
            echo '<h1 style="color:red">' . $errorr . '</h1><br><h2>Check for Other way</h2>';
        } else {
            if (mysqli_num_rows($result)) {

?>
                <hr style="width:40%">
                <center>
                    <h2>Predicted Diabetes Reports </h2>


                    <table style="width:100%;padding:20px;text-align:center;">
                        <tr>
                            <td>Sl No</td>
                            <td>Aadhar</td>
                            <td>Date and Time</td>
                            <td>Number of Pregnencies</td>
                            <td>Glucose</td>
                            <td>Blood Pressure</td>
                            <td>Skin Thickness</td>
                            <td>Insulin Level</td>
                            <td>BMI</td>
                            <td>Pedigree Function</td>
                            <td>age</td>
                            <td>Results</td>
                        </tr>
                        <tr>

                            <?php
                            $i = 1;

                            $Nrow = mysqli_num_rows($result);

                            while ($i <= $Nrow) {
                                echo ' <td>' . $i . '</td>';
                                $rows = mysqli_fetch_assoc($result);
                                foreach ($rows as $value) {
                                    echo "<td>" . $value . "</td>";
                                }

                                echo '</tr>';
                                $i += 1;
                            }
                            ?>
                        </tr>
                    </table>

                </center>


<?php
                echo '<script>window.print()</script>';
            }
        }
    }
}
?>
<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    td {
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>