<?php
require_once "../assets/conn.php";



$url = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
$parts = parse_url($url);
$output = [];
parse_str($parts['query'], $output);

$rid = $output['rid'];

$sql1 = "SELECT * ,  p.name 'pname',pr.pname 'pres'
            from reqapp r
            join patient p on p.id=r.pid
            join doctor d on d.did=r.did
            join patient_sym ps on ps.rid =r.reqid
            join patient_pre pp on pp.rid=r.reqid
            join patient_disease pd on pd.rid=r.reqid
            join prescription pr on pr.preid=pp.preid
            join disease  dis on dis.did=pd.did
            join symptoms ss on ss.sid=ps.sid
            where r.reqid='$rid';";



$sql = "SELECT * FROM reqapp where reqid='$rid';";
$result = mysqli_query($conn, $sql);
$Nrow = mysqli_num_rows($result);

$rows = mysqli_fetch_assoc($result);
$patid = $rows['pid'];
$doctid = $rows['did'];
$disease = $rows['disease'];
$rdate=$rows['rdate'];
$rtime=$rows['rtime'];

$sql = "SELECT * FROM patient where id='$patid';";
$result = mysqli_query($conn, $sql);
$Nrow = mysqli_num_rows($result);

$rows = mysqli_fetch_assoc($result);
$pname = $rows['name'];
$paddress = $rows['address'];
$pblood = $rows['blood'];
$pdob = $rows['dob'];
$paadhar = $rows['aadhar'];
$pwt = $rows['weight'];
$pht = $rows['height'];
$father = $rows['father'];
$mother = $rows['mother'];
$pmobile = $rows['mobile'];
$blood = $rows['blood'];
$gender = $rows['gender'];


$sql = "SELECT * FROM doctor where did='$doctid';";
$result = mysqli_query($conn, $sql);
$Nrow = mysqli_num_rows($result);
$rows = mysqli_fetch_assoc($result);

$dname = $rows['name'];
$dhospital = $rows['hospital'];
$dspec = $rows['specialization'];


$sql = "SELECT * FROM patient_disease pd
     join patient_pre pp on pp.rid=pd.rid
    join patient_sym ps on ps.rid=pd.rid
     join symptoms s on s.sid=ps.sid
     join disease d on d.did=pd.did
     join prescription p on p.preid=pp.preid
    where pd.rid='$rid';";
$result = mysqli_query($conn, $sql);
$Nrow = mysqli_num_rows($result);

// echo $Nrow;
$adisease = "<table>";
$symptoms = "<table>";
$prescription = "<table>";

$adis = array();
$asym = array();
$apres = array();

while ($rows = mysqli_fetch_assoc($result)) {
    array_push($adis, $rows['dname']);
    array_push($asym, $rows['sname']);
    array_push($apres, $rows['pname']);
}
$adis = array_unique($adis);
$asym = array_unique($asym);
$apres = array_unique($apres);

foreach ($adis as $name) {
    $adisease .= '<tr><td>' . $name . '</td></tr>';
}
foreach ($asym as $name) {
    $symptoms .= '<tr><td>' . $name . '</td></tr>';
}
foreach ($apres as $name) {
    $prescription .= '<tr><td>' . $name . '</td></tr>';
}


$adisease .= "</table>";
$symptoms .= "</table>";
$prescription .= "</table>";


$errorr = mysqli_error($conn);
if ($errorr) {

    echo '<h1 style="color:red">' . $errorr . '</h1><br><h2>Check for Other way</h2>';
} else {
    $rows = mysqli_fetch_assoc($result);
    echo $rows;
    echo '

    <center>
    <h1>Siddaganga Instute of Technology</h1>
    <h2>Online E-Health Records</h2>
    <h2>Report generated by '.$dname.' from '.$dhospital.'</h2>
    <br>
    <hr>
    <button style="float: right;width:70px;padding:13px;margin-right:30px;"><a target="_blank" href="/hospital/E-Hospital-Management/data/reportPatient.php?rid='.$rid.'">print</a></button>

    <table style="width:40%;text-align:center;">
    <tr>
    <td>Name</td>
    <td>' . $pname . '</td>
    </tr>
    <tr>
    <td>Patient ID</td>
    <td>' . $patid . '</td>
    </tr>
    <tr>
    <td>Father Name</td><td>' . $father . '</td>
    </tr>
    <tr> 
    <td>Mother Name</td><td>' . $mother . '</td>
    </tr>
    <tr> 
    <td>Gender</td><td>' . $gender . '</td>
    </tr>
    <tr><td>blood group</td><td>' . $pblood . '</td></tr>
    <tr>
    <td>
    DOB</td> <td>' . $pdob . '</td></tr>
    <tr><td>Mobile</td> <td>' . $pmobile . '</td>  </tr>
    <tr><td>weight</td> <td>' . $pwt . '</td>  </tr>
    <tr><td>Height</td> <td>' . $pht . ' feet</td>  </tr>
   
    </table>
    <br>
    </center>
    ';


?>
    <center>

        <table style="width:60%;padding:12px;">
            <tr>
                <td>Request ID</td>
                <td><?php echo $rid; ?></td>
            </tr>
            
            <tr>
                <td>Date and Time</td>
                <td><?php echo $rdate,' ',$rtime; ?></td>
            </tr>            <tr>
                <td>Hospital</td>
                <td><?php echo $dhospital; ?></td>
            </tr>
            <tr>
                <td>Doctor Name</td>
                <td><?php echo $dname; ?></td>
            </tr>

            <tr>
                <td> Disease</td>
                <td><?php echo $adisease; ?></td>
            </tr>
            <tr>
                <td>Prescription Given</td>
                <td><?php echo $prescription; ?></td>
            </tr>
            <tr>
                <td>Symptoms</td>
                <td><?php echo $symptoms; ?></td>
            </tr>
        </table>

     
    <?php
   echo '<script>window.print()</script>';

}


    ?>

    <style>
        table {
            border-collapse: collapse;
            width: 100%;
               }

        td {
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>